### ISSUE TITLE
Version tag update to avoid confusion

### ISSUE THREAD

**Issue by ShorelineCrypto** [ShorelineCrypto/NewEnglandCoin#9]
Dave at bitcointalk reported that there are still clients mining old chains. 

The version tag needs to be updated to new number and all linux/mac/windows clients binary 
needs to be compiled.

**Comment by miningdave** [comment]
I have connections blocked at the firewall so it has 0 connections now, but you can see that the last block mined was yesterday but only # 1304628 vs 140xxx that the other chain is on.

![image](https://user-images.githubusercontent.com/61623195/79161198-0e3c4f80-7da9-11ea-89eb-f3f0b2523d1d.png)

**Comment by ShorelineCrypto** [comment]
Indeed, just found out that there is mining pool  https://yiimp.coin-mining.eu/  of NENG on this same old chain.  I will post in bitcointalk to reach out to remind them on the hard fork.

**Comment by ShorelineCrypto** [comment]
This version confusion should be fixed. The new GUI and CLI wallet with new logo also included a version tag change. Here is new latest:

v0.8.7.5-randomSpike-v1.4.x

Strictly speaking, the version is still v0.8.7.5 from above. But client includes the randomSpike and v1.4.x clearly indicates where is the software version stand on NENG github branch.
